dist: trusty
language: csharp
mono: none
dotnet: 2.1.202
solution: core21.sln
script:
  - cd core21
  - dotnet restore
  - dotnet build
  - dotnet test
services:
  - mysql
before_install:
  - cd core21
  - mysql -u root --password="" < database/novel.sql
